### ISSUE TITLE
Need to validate confirmed transactions with counterparty before sending them along

### ISSUE THREAD

**Issue by deweller** [tokenly/xchain#2]
If a user crafts a malicious send when they do not actually have the funds available, xchain needs to validate this transaction with counterpartyd before sending a confirmed notice.

**Comment by loon3** [comment]
Are you storing transactions parsed by xchain even after they're parsed by counterpartyd?

**Comment by deweller** [comment]
@loon3 - yes.  XChain stores the transaction data as parsed by XChain.  But when this issue is fixed, it will only mark counterparty transactions as valid when validated by counterpartyd.

**Comment by AdamBLevine** [comment]
Woot!
