### ISSUE TITLE
Deal with transaction malleability

### ISSUE THREAD

**Issue by deweller** [tokenly/xchain#21]
Bitcoin transaction IDs can change before transactions are mined into a block.

To the bitcoin network, the first transaction becomes invalidated and a second transaction is confirmed that spends the same UTXOs.  This is just a special case of a double spend.

XChain should notify clients of unconfirmed transactions that are invalidated.  Then the clients can deal with invalidated transactions as they see fit.

For bonus points, provide the transaction ID of the new transaction that invalidated the old transaction.

**Comment by cryptonaut420** [comment]
Not sure if it helps in your situation, but here is my attempt at handling malleability in Token Slot (so far so good) https://github.com/tokenly/token-slot/commit/d43559adef934d9c49901ca918736002c20c9e25 and https://github.com/tokenly/token-slot/commit/c94e06d3c72fb5ba14f893df5a7c55a1378db4b3

Basically I generate an "internal tx id" for each transaction that I'm notified about, using data from the transaction that wouldn't be altered from malleability. I then look at any transactions which I already know about, compare the internal IDs, and if it's a match then I update with the new transaction ID, keep the old ID as well and mark that it's a malleated TX for recording purposes.

**Comment by deweller** [comment]
Yep.  This will be useful.  I will add this as a `transactionFingerprint` field when XChain sends notifications.
