### ISSUE TITLE
address balances do not take into account non-divisible tokens

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/xchain#24]
currently it is returning the value in satoshis (x \* 100,000,000) for all assets. non-divisible assets should not be multiplied like that

**Comment by deweller** [comment]
`/api/v1/balances/{address}` endpoint is supposed to already account for divisible and non-divisible assets.

The `balances` value will always return the correct float value and `balancesSat` will always return the value in satoshis, even if the asset is indivisible.

This is working in my tests.

To get the correct human readable balance, just use the float value, or use the balancesSat value divided by 100000000.

**Comment by cryptonaut420** [comment]
I think the issue is actually that the balance in satoshis is not 1,000,000,000 for an indivisible asset (e.g EARLY) - it's just 1.

**Comment by cryptonaut420** [comment]
disregard above comment
