### ISSUE TITLE
Better Coin Selection Algorithm

### ISSUE THREAD

**Issue by deweller** [tokenly/xchain#25]
XChain looks first to choose a combination of UTXOs (coins) that will add up to exactly the right amount of BTC to send.  This is good because it can compose a smaller transaction with no change outputs.

But on the whole, the TXO Chooser algorithm needs an upgrade.  It does not work when the number of TXOs grows above 10 or so.  The number of possible combinations grows exponentially and it can’t possibly look at all of them.  So, as a fallback, it just spends all the UTXOs and creates change.  This causes problems for some uses of XChain.

Consider using a modified version of the Bitcoin Core coin selection algorithm:
http://bitcoin.stackexchange.com/questions/1077/what-is-the-coin-selection-algorithm

Include fee estimation as part of the selection algorithm.

**Comment by cryptonaut420** [comment]
I feel like this may be overcomplicating it a bit. The primary issue is that there is a limit to the size of a transaction before bitcoind (or even the network in general) will reject it for being too large. The current xchain coin selection algorithm falls back to "spend all utxos" if the possible change combinations get too high. Sometimes "all utxos" is simply too many, thus it ends up failing any time you want to spend more than a handful (e.g you might only need 15 utxos, but after 10 it gives up and tries to spend all 200 of them).

The easiest solution IMO would be to replace the "use all utxos" fallback with "use up to MAX_UTXOS", and simply stop caring about always using only the most efficient utxo-set. There is also different functions for different utxo selection strategies already, so maybe we can have one which does a very simple sort-by-amount for the utxo list and just grabs >= what it needs and calls it a day (for example, see my sendfromaddress() function which does exactly this and works fine with using vanilla bitcoin commands https://github.com/tokenly/tokenly-cms/blob/master/slick/API/Bitcoin.php )

**Comment by deweller** [comment]
Ok.  Instead of reworking the entire algorithm, I did this.

If the the number of UTXOs are too large to try every combination, fall back to this naive algorithm:

1) Beginning with the smallest UTXO and sum each UTXO value until the required amount is met.  If the number of UTXOs chosen is greater than 145, give up go to step 2.
2) Begin with the largest UTXO and sum each UTXO value until the required amount is met.  If the number of UTXOs chosen is greater than 145, give up and throw an error.
