### ISSUE TITLE
sweep command fails

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/xchain#29]
I've tested this out a few times now and keep getting the same results. Sending a sweepAllAssets() call from xchain-client throws an exception "unable to complete this request". Looking at the address on the blockchain, it does actually send a transaction, spending all outputs to the desired destination... however it seems to send all the BTC first and is left with nothing to send any leftover assets, and even with only BTC in there it still throws an error. 

Looking at the xchain logs, here is an example of what I'm seeing:

```
[2016-04-30 06:22:01] local.INFO: send.requested {
    "destination": "15fx1Gqe4KodZvyzN6VUSkEmhCssrM1yD7",
    "quantity": null,
    "fee": 0.0001,
    "dust_size": 5.43e-5,
    "asset": "ALLASSETS",
    "sweep": true,
    "requestId": null,
    "account": null,
    "unconfirmed": null,
    "utxo_override": null,
    "user_id": "2",
    "payment_address_id": "35",
    "quantity_sat": 0,
    "is_sweep": true,
    "destinations": ""
}
[2016-04-30 06:22:01] local.DEBUG: buildComposedTransaction $float_quantity=null $asset="BTC" is_sweep=true
[2016-04-30 06:22:03] local.ERROR: error.sweep {
    "error": "Balance of 0 was insufficient to debit 0 (unconfirmed) BTC from default",
    "code": 0,
    "line": 62,
    "file": "/var/www/xchain/app/Repositories/LedgerEntryRepository.php"
}
[2016-04-30 06:22:03] local.DEBUG: new send TXO: 67979d79adf9fe31c701ae8ef81b9a08bd76624042e76ff386972af7fcbaa529:0/5430 sending to 75a538c9-f192-4487-b6dc-c5393c5445a6
[2016-04-30 06:22:03] local.DEBUG: new send TXO: 9d698267073ab4e958f81033b7ecd3596d7714a586bffa76cc3193e7b401fa0b:7/12930 sending to 75a538c9-f192-4487-b6dc-c5393c5445a6
[2016-04-30 06:22:03] local.DEBUG: new send TXO: 9d698267073ab4e958f81033b7ecd3596d7714a586bffa76cc3193e7b401fa0b:8/12500 sending to 75a538c9-f192-4487-b6dc-c5393c5445a6
[2016-04-30 06:22:03] local.ERROR: handleUnconfirmedTransaction.error {
    "error": "Balance of 0 was insufficient to debit 0.0003086 (confirmed) BTC from default",
    "code": 0,
    "line": 62,
    "file": "/var/www/xchain/app/Repositories/LedgerEntryRepository.php",
    "id": "3147774",
    "txid": "22c5dd4be1b8e58de8ce0b70394ba1c34495f98b45c028e454dd74f24e864621"
}
```

As you can see, transaction ID does get generated and even broadcasted, but it throws that Balance 0 was insufficient error anyway, which seems to kill the request. Additionally, if you look at the source address (1FRbXGBxB6pxBgZyC2HmXYQNBC3dhHwuTC) there is 75 LTBC left that it should have sweeped but didn't try (even though there should have been enough leftover btc to pay for fees). Sometimes it does look like it attempts to sweep the extra LTBC, but "Balance of 0 was insufficient to debit X (confirmed) LTBCOIN" similarly shows up.

**Comment by deweller** [comment]
So, is this what a failure scenario would look like?

The address contains:

``` json
{
     "BTC": 0.001,
     "LTBCOIN": 75
}
```

I call POST `/api/v1/sends/{addressId}` with

``` json
    "destination": "15fx1Gqe4KodZvyzN6VUSkEmhCssrM1yD7",
    "asset": "ALLASSETS",
    "sweep": true,
```

And XChain returns a `balance was insufficient` error.

Is that correct?

**Comment by cryptonaut420** [comment]
Yeah pretty much. On the client side all I get is a "unable to complete request", but on xchain logs I am seeing the "Balance of X insufficient to debit" error popping up, and yeah doesn't bother sending the assets only sends the BTC. The BTC balance in this case  was 0.00030860 and 75 LTBCOIN, with fee set to 0.0001 and dust value to 0.0000543
