### ISSUE TITLE
max_utxos option in cleanup command does not work quite as expected

### ISSUE THREAD

**Issue by cryptonaut420** [tokenly/xchain#30]
The new CleanupUTXOs command has a parameter for "max_utxos". 

How I thought this worked was that it was basically "up to how many utxos do you want to consolidate". Meaning that if there was say 400 utxos sitting there, I could set max_utxos=150 and I would be left with 251. Then call the command again and be left with 102, then a third time and be left with 1 single fully consolidated utxo. 

How it actually appears to work is "how many utxos do you want to be left with". Meaning that if there is 400 utxos and I set max_utxos=150, it tries to spend all 400 of them at once and create 150 new outputs.  Which of course would probably just fail because that is way too big of a tx. 

It needs to work like the former rather than the latter, because the situation where you would want/need to clean up your unspent outputs, is also the exact situation where you probably have way too many outputs to spend all at once. Also consolidating is about reducing to the smallest number of utxos possible, if a specific utxo count is required than the priming functions already accomplish the same.

**Comment by deweller** [comment]
Ok - I will reverse the math on the UTXO count calculation.

I will put a hard limit on the number of UTXOs.  Is a maximum of 150 safe?  Would that ever create a transaction that is too big?

**Comment by cryptonaut420** [comment]
cool. Yeah that should be fairly safe, I don't think it would ever make too large of a tx unless you were also creating a lot of new outputs with it. IIRC the max tx size for standard transactions is 100Kb, but that's difficult to tell until tx is already generated and signed.
