### ISSUE TITLE
file doesnt exist

### ISSUE THREAD

**Issue by ghost** [tokenly/xchain#41]
> /xchain/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /xchain/bootstrap
> /autoload.php on line 17

**Comment by deweller** [comment]
You will need to do a `composer install` before running XChain.

XChain requires quite a bit of infrastructure and setup to be useful.  Can you email team@tokenly.com and let us know what you have in mind?

**Comment by ghost** [comment]
Thanks. My bad. Never used composer. Got it working now.
